version: '2'
services:
    example-server:
        image: stealthii/chocolate-server
        mem_limit: 300000000
        ports:
            - 0.0.0.0:2342:2342/udp
        environment:
            port: 2342
            servername: "Docker Doom Server"
            privateserver: "false"
    private-newsync:
        image: stealthii/chocolate-server
        mem_limit: 300000000
        ports:
            - 0.0.0.0:7045:7045/udp
        environment:
            port: 7045
            servername: "Private Doom Server (newsync)"
            privateserver: "true"
            newsync: "true"
